In [2]:
import pandas as pd

# 2 pd的Series

In [5]:
# 通过 list 构建 Series
ser_obj = pd.Series(range(10, 20))
print(ser_obj)
print(type(ser_obj))

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
<class 'pandas.core.series.Series'>


In [4]:
# 获取数据
print(ser_obj.values)
# 获取索引
print(ser_obj.index)

[10 11 12 13 14 15 16 17 18 19]
RangeIndex(start=0, stop=10, step=1)


In [6]:
#通过索引获取数据
print(ser_obj[0])
print(ser_obj[8])

10
18


In [9]:
# 通过 dict 构建 Series
year_data = {2001: 17.8, 2002: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print(ser_obj2.index)
print(ser_obj2[2001])

2001    17.8
2002    20.1
2003    16.5
dtype: float64
Index([2001, 2002, 2003], dtype='int64')
17.8


Series 对象本质上由两个数组构成，
一个数组构成对象的键(index，索引)，一个数组构成对象的值(values)， 键->值

# 3 DataFrame
DataFrame 是一个表格型的数据结构，它含有一组有序的列，每列可以是不同类型的值。DataFrame 既有行索引也有列索引，它可以被看做是由 Series 组成的字典（共用同一个索引），数据是以二维结构存放的。

In [10]:
import numpy as np
import pandas as pd
# 通过 ndarray 构建 DataFrame
t = pd.DataFrame(np.arange(12).reshape((3,4)))
print(t)
array = np.random.randn(5,4) # 生成一个 5×4 的随机数组，元素服从 标准正态分布 N(0,1)
print(array)
df_obj = pd.DataFrame(array)
print(df_obj.head())

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
[[-1.01529077  0.22059797  0.44179763  0.68709494]
 [ 0.49933476 -0.51666065  0.53080499  0.07521809]
 [-0.24362207 -0.4855478  -0.43260429 -0.49785504]
 [ 0.28341933 -2.01556952  1.86548938  0.66188456]
 [-1.63418976 -1.0246115  -0.95420031  0.4107219 ]]
          0         1         2         3
0 -1.015291  0.220598  0.441798  0.687095
1  0.499335 -0.516661  0.530805  0.075218
2 -0.243622 -0.485548 -0.432604 -0.497855
3  0.283419 -2.015570  1.865489  0.661885
4 -1.634190 -1.024611 -0.954200  0.410722


DataFrame 对象既有行索引，又有列索引  
行索引，表明不同行，横向索引，叫 index，0 轴，axis=0  
列索引，表名不同列，纵向索引，叫 columns，1 轴，axis=1

In [13]:
# 通过 dict 构建 DataFrame
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1,index=list(range(4)),dtype='float32'),
             'D': np.array([3] * 4,dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'wangdao' }
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)
d1={"name":["xiaoming","xiaogang"],"age":[20,32],"tel":
[10086,10010]}
print(pd.DataFrame(d1))
d2 =[{"name" : "xiaohong" ,"age" :32,"tel" :10010},{ "name":
"xiaogang" ,"tel": 10000} ,{"name":"xiaowang" ,"age":22}]
print(pd.DataFrame(d2))

   A          B    C  D       E        F
0  1 2019-09-26  1.0  3  Python  wangdao
1  1 2019-09-26  1.0  3    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  3       C  wangdao
       name  age    tel
0  xiaoming   20  10086
1  xiaogang   32  10010
       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN
